### ISSUE TITLE
Problème de bypass schedule tiko sur HA

### ISSUE THREAD

**Issue by YNK22** [marvinroger/hass-addon-tiko#11]
Bonjour à tous,
J'ai un soucis sur la gestion de mes radiateurs, j'utilise l'intégration versatile thermostat ainsi que l'addon Tiko, par contre les capteurs de température de tiko ont une température erroné du coup si par exemple mon capteur de température zigbee à une température de 18 (avec une température cible de 17) mais que le capteur de tiko à une température de 16 il va quand même chauffer alors que moi je veux qu'il bypass complètement tiko pour être géré uniquement par versatile thermostat.
Cordialement.

**Comment by Swiiney** [comment]
Quand tu regardes le fonctionnement de versatile thermostat en "over climate", le cas pour Tiko. Il ne fait que donner la température cible au climate sous-jacent et donc c'est celui ci qui va gérer l'allumage et l'extinction pour atteindre cette cible.
Je ne pense pas qu'il soit possible de bypasser la gestion du thermostat par Tiko puisque c'est l'essence même de Tiko.
Si tu veux faire ça, il vaut mieux que tu installe toi-même des modules fil-pilote et une sonde de température que tu coupleras dans Versatile Thermostat.

Par contre cela me semble anormal que les sondes de température de Tiko soient fausses. Leur as-tu remonté le problème ?

**Comment by YNK22** [comment]
Salut et merci du retour, oui je leur ai fait un mail mais je n'ai pas eu de retour pour le moment.
Je pense que le problème est dû qu'elles sont collés au mur et suffit que le mur soit froid pour qu'il détecte une température inférieure à la température réelle.

Est-ce que tu as des conseils à me donner dans la configuration de versatile thermostat ?

**Comment by Swiiney** [comment]
En fait j'ai abandonné pour Tiko 😁 Trop de galère.

**Comment by marvinroger** [comment]
Hello @YNK22 !

Ce que tu peux faire est complètement possible en l'état :

* Tu peux créer un switch virtuel pour chaque radiateur avec le [Template Switch](https://www.home-assistant.io/integrations/switch.template/)
* Allumer et éteindre un radiateur dans tiko ne veut rien dire, tu ne peux que définir des températures. On peut donc considérer que "éteindre" veut dire "mettre la température au minimum", soit 7 degrés, et "allumer" veut dire "mettre la température au maximum", soit 25 degrés
* Tu n'as plus qu'à faire en sorte que le `turn_on` appelle le service `climate.set_temperature` avec 25 degrés, et `turn_off` appelle `climate.set_temperature` avec 7 degrés`

Il suffit de brancher ces switch virtuels à versatile thermostat et tu bypasseras complètement les capteurs de température de tiko (tant qu'ils ne renvoient pas de valeurs trop déconnantes non plus, par exemple moins de 7 degrés).
