### ISSUE TITLE
ERROR (7): Error from MQTT client

### ISSUE THREAD

**Issue by phid78** [marvinroger/hass-addon-tiko#12]
Bonjour @marvinroger 
Depuis quelques jours (je crois la dernière mise a jour core_2024.3.0), j'ai une erreur en boucle alors que je n'ai rien touché : 

```
[19:27:36.416] ERROR (7): Error from MQTT client
    err: {
      "type": "Error",
      "message": "getaddrinfo ENOTFOUND core-mosquitto",
      "stack":
          Error: getaddrinfo ENOTFOUND core-mosquitto
              at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)
      "errno": -3007,
      "code": "ENOTFOUND",
      "syscall": "getaddrinfo",
      "hostname": "core-mosquitto"
    }
[19:27:36.416] WARN (7): Disconnected from MQTT broker, will try to reconnect
```

mes réglages : 
Mon pilotage elec
Email
Password

En te remerciant par avance de jeter un oeil ;)

**Comment by marvinroger** [comment]
Bonjour ☺️

L'add-on fonctionne bien avec les dernières versions, tu es sûr que l'addon MQTT est bien démarré ? Tu as tenté de simplement redémarrer ?

**Comment by phid78** [comment]
j'ai relancer la VM et ca marche, désolé de t'avoir deranger et merci pour ta rapidité.
