### ISSUE TITLE
deconnection intempestive

### ISSUE THREAD

**Issue by phid78** [marvinroger/hass-addon-tiko#16]
Bonjour, 
Depuis que j'ai rallumé les radiateurs il y a une semaine, le systeme a fonctionné quelques jours et ensuite plus rien. 
Je ne suis pas sur que le probleme vienne de cet addon alors j'ai essayé plusieurs chose : 
en preambule, quasi systematiquement, des qu'un changement de consigne avait lieu, le systeme entier perdait la connection. Je suis sur une VM de la freebox delta (peut etre s'agit il d'un probleme de ram ?!)
J'ai essayé de configurer une compte mqtt dans mqtt et dans l'addon tiko, mais impossible d'avoir une remontée d'information, j'ai essayé en activant Require Client Certificate sur mqtt, pas de changement. j'ai relancer plusieur fois la vm sans succes.
Finalement, ce matin, j'ai désinstallé mqtt et l'addon, relancer la VM, reinstallé mqtt avec les reglages de base puis l'addon avec juste mon mail et mot de passe. Sur les 2 addon, j'ai laissé lancer au demarrage, chien de garde et mise a jour auto. J'ai enfin eu une remontée d'information, mais en cours de journée a nouveau des pertes de connection et l'addon tiko s'est arreté. Mqtt tourne toujours.
Je viens de relancer mqtt, voila le log

> [19:32:13] INFO: Certificates found: SSL is available
> cont-init: info: /etc/cont-init.d/mosquitto.sh exited 0
> cont-init: info: running /etc/cont-init.d/nginx.sh
> cont-init: info: /etc/cont-init.d/nginx.sh exited 0
> s6-rc: info: service legacy-cont-init successfully started
> s6-rc: info: service legacy-services: starting
> services-up: info: copying legacy longrun mosquitto (no readiness notification)
> services-up: info: copying legacy longrun nginx (no readiness notification)
> [19:32:15] INFO: Starting NGINX for authentication handling...
> s6-rc: info: service legacy-services successfully started
> [19:32:15] INFO: Starting mosquitto MQTT broker...
> 2024-10-05 19:32:16: Warning: Mosquitto should not be run as root/administrator.
> 2024-10-05 19:32:16: mosquitto version 2.0.18 starting
> 2024-10-05 19:32:16: Config loaded from /etc/mosquitto/mosquitto.conf.
> 2024-10-05 19:32:16: Loading plugin: /usr/share/mosquitto/go-auth.so
> 2024-10-05 19:32:16:  ├── Username/password checking enabled.
> 2024-10-05 19:32:16:  ├── TLS-PSK checking enabled.
> 2024-10-05 19:32:16:  └── Extended authentication not enabled.
> 2024-10-05 19:32:16: Opening ipv4 listen socket on port 1883.
> 2024-10-05 19:32:16: Opening ipv6 listen socket on port 1883.
> 2024-10-05 19:32:16: Opening websockets listen socket on port 1884.
> 2024-10-05 19:32:16: Opening ipv4 listen socket on port 8883.
> 2024-10-05 19:32:16: Opening ipv6 listen socket on port 8883.
> 2024-10-05 19:32:16: Opening websockets listen socket on port 8884.
> 2024-10-05 19:32:16: mosquitto version 2.0.18 running
> 2024-10-05 19:32:18: New connection from ::1:41706 on port 1883.
> 2024-10-05 19:32:18: Client <unknown> disconnected due to protocol error.
> [19:32:20] INFO: Successfully send discovery information to Home Assistant.
> [19:32:20] INFO: Successfully send service information to the Supervisor.
> 2024-10-05 19:32:24: New connection from 172.30.32.1:43851 on port 1883.
> 2024-10-05 19:32:24: New client connected from 172.30.32.1:43851 as 6zGmSTc8Xmv2nG4jYIAKxb (p2, c1, k60, u'homeassistant').
> 2024-10-05 19:33:58: New connection from 172.30.32.2:49956 on port 1883.
> 2024-10-05 19:33:58: Client <unknown> closed its connection.
> 2024-10-05 19:34:49: New connection from 172.30.33.3:56520 on port 1883.
> 2024-10-05 19:34:49: New client connected from 172.30.33.3:56520 as mqttjs_d564384f (p2, c1, k60, u'addons').
> 2024-10-05 19:35:03: Client mqttjs_d564384f closed its connection.
> 2024-10-05 19:35:58: New connection from 172.30.32.2:42234 on port 1883.
> 2024-10-05 19:35:58: Client <unknown> closed its connection.
> 2024-10-05 19:36:55: New connection from 172.30.33.3:36802 on port 1883.
> 2024-10-05 19:36:55: New client connected from 172.30.33.3:36802 as mqttjs_025ee660 (p2, c1, k60, u'addons').
> 2024-10-05 19:37:56: Client mqttjs_025ee660 closed its connection.
> 2024-10-05 19:37:59: New connection from 172.30.32.2:56024 on port 1883.
> 2024-10-05 19:38:00: Client <unknown> closed its connection.
> 2024-10-05 19:38:41: New connection from 172.30.33.3:49834 on port 1883.
> 2024-10-05 19:38:42: New client connected from 172.30.33.3:49834 as mqttjs_67c136af (p2, c1, k60, u'addons').
> 2024-10-05 19:38:49: Client mqttjs_67c136af closed its connection.
> 2024-10-05 19:40:01: New connection from 172.30.32.2:54022 on port 1883.
> 2024-10-05 19:40:01: Client <unknown> closed its connection.
> 2024-10-05 19:41:14: New connection from 172.30.33.3:37166 on port 1883.
> 2024-10-05 19:41:14: New client connected from 172.30.33.3:37166 as mqttjs_49f1ee7f (p2, c1, k60, u'addons').
> 2024-10-05 19:42:01: New connection from 172.30.32.2:43334 on port 1883.
> 2024-10-05 19:42:02: Client <unknown> closed its connection.
et ainsi de suite

J'ai relancer l'addon tiko, voila son log

> [19:34:24] INFO: Running in Home Assistant mode
> [19:34:25] INFO: MQTT_BROKER_URL not set, using MQTT addon service...
> [19:34:48.526] INFO (6): List of properties
>     0: {
>       "id": xxxxxx,
>       "name": "xxxxxxx"
>     }
> [19:34:50.643] INFO (6): Connected to MQTT broker
> [19:34:50.643] INFO (6): Subscribing to topic
>     topic: "homeassistant/status"
> [19:34:51.389] INFO (6): Subscribing to topic
>     topic: "homeassistant/climate/tiko_10xxxxxx/set"
> [19:34:51.447] INFO (6): Subscribing to topic
>     topic: "homeassistant/climate/tiko_10xxxxx/set"
> [19:34:51.450] INFO (6): Subscribing to topic
>     topic: "homeassistant/climate/tiko_10xxxxx/set"
> [19:34:51.452] INFO (6): Subscribing to topic
>     topic: "homeassistant/climate/tiko_10xxxxx/set"
> [19:34:51.455] INFO (6): Connection ready

Les infos remontent pendant 1 min, puis indisponible et le addon tiko est arreté, il redemarre tout seul, mais pas de remontée des radiateurs (toujours indisponible)
Le raffraichissement du journal donne ceci : 

> [19:39:15] INFO: Running in Home Assistant mode
> [19:39:16] INFO: MQTT_BROKER_URL not set, using MQTT addon service...
> 
> [19:39:56] INFO: Running in Home Assistant mode
> [19:39:56] INFO: MQTT_BROKER_URL not set, using MQTT addon service...

JE retourne voir les radiateurs, ils sont la, je reviens dans modules complementaires, j'ai un message de perte de connection de HA, je raffraichit le log et j'ai  : 

> [19:39:56] INFO: Running in Home Assistant mode
> [19:39:56] INFO: MQTT_BROKER_URL not set, using MQTT addon service...
> 
> [19:40:49] INFO: Running in Home Assistant mode
> [19:40:50] INFO: MQTT_BROKER_URL not set, using MQTT addon service...
> [19:41:13.976] INFO (7): List of properties
>     0: {
>       "id": 100xxxxx,
>       "name": "xxxxxxxx"
>     }
> [19:41:15.093] INFO (7): Connected to MQTT broker
> [19:41:15.093] INFO (7): Subscribing to topic
>     topic: "homeassistant/status"
> [19:41:15.360] INFO (7): Subscribing to topic
>     topic: "homeassistant/climate/tiko_100xxxx/set"
> [19:41:15.363] INFO (7): Subscribing to topic
>     topic: "homeassistant/climate/tiko_1000xxxx/set"
> [19:41:15.365] INFO (7): Subscribing to topic
>     topic: "homeassistant/climate/tiko_10xxxx/set"
> [19:41:15.368] INFO (7): Subscribing to topic
>     topic: "homeassistant/climate/tiko_1xxxx/set"
> [19:41:15.371] INFO (7): Connection ready
> 
> [19:42:47] INFO: Running in Home Assistant mode
> [19:42:48] INFO: MQTT_BROKER_URL not set, using MQTT addon service...

Je retourne voir les radiateurs, ils sont la et deviennent indisponible quasi immédiatement.
En gros c'est ca en boucle.

Un coup de main serait pas de refus, il commence a faire froid...

**Comment by bollee23** [comment]
Je ne vais pas vous être d'une grande aide, mais j'ai constaté très exactement le même comportement ces derniers jours. Je suis également sur une VM sur une freebox (Ultra) et j'ai pu hier retrouver un fonctionnement temporaire après redémarrage de la VM (les arrêts/redémarrages de l'add-on ne semblant rien arranger et l'add-on semblant s'éteindre au bout de qq minutes ou un peu plus après redémarrage de la VM). Mes logs sont quasi identiques.
A noter cependant que je suis passé très récemment sur HA sur freebox (j'ai reçu ma fb il y a un mois) après un essai sur RPi cet été où je n'ai pas trop prêté attention au fonctionnement de l'add-on tiko+MQTT.
Ceci étant, cela n'empêche pas le système Tiko de fonctionner, le contrôle par le site internet ou l'app dédiée fonctionne bien.

**Comment by bollee23** [comment]
Les choses semblent remarcher de mon côté :-)

**Comment by phid78** [comment]
J'ai changé la RAM il y a 4 jours, depuis je n'ai pas de problème.
J'ai laissé ouvert le temps de voir si ca replantait et si d'autre rencontraient le soucis.

**Comment by bollee23** [comment]
C'est bien possible en effet d'autant que sur la FB Ultra la ressource RAM est très limitée (pour avoir 2 VM, le max, il faut se serrer la ceinture à 1Go par VM). Comme ma config se stabilise (je n'installe plus rien de nouveau sous HA) je me dis la pression sur la RAM est redescendue (autour des 85% d'utilisation qd même).

**Comment by noiwid** [comment]
Les 2 Go de base sur la Freebox c'est effectivement un peu léger pour faire
tourner des VM 😉

**Comment by marvinroger** [comment]
Bonjour,

Vous en avez déduit que le souci est donc un manque de RAM, donc rien d'inhérent à cet add-on, je ferme cette issue 😉
