### ISSUE TITLE
Déploiement Docker indépendant

### ISSUE THREAD

**Issue by SylvainDx** [marvinroger/hass-addon-tiko#18]
Bonjour,

Merci beaucoup pour ce developpement.
J'ai un HA qui tourne déjà dans un docker, donc pas de possibilité de déployer les add-on directement.

J'ai trouvé sur un forum le compose suivant : 
`services:
  tiko:
    container_name: tiko
    image: "ghcr.io/marvinroger/hass-addon-tiko-amd64:latest"
    restart: unless-stopped
    environment:
      - TIKO_PROVIDER=tiko
      - TIKO_EMAIL=mon@email.com
      - TIKO_PASSWORD=passwordtiko
      - MQTT_BROKER_URL="mqtt://mqtt_broker_ip:1883"
      - MQTT_USERNAME=mqtt_user
      - MQTT_PASSWORD=mqtt_password
      - UPDATE_INTERVAL_MINUTES=1
     depends_on:
      - mosquitto`

Serait-il possible de documenter les options ou cette méthode de déploiement ?
Pour l'heure j'ai une petite saturation de l'api pour aller plus loin et m'assurer du bon fonctionnement.
mais j'ai déjà une erreur qui dit : 
`curl:  (6) Could nor resolve host: supervisor` 
lié a n'en pas douter au contexte hors HAOS mais est-il sans conséquence ?

**Comment by marvinroger** [comment]
Bonjour Sylvain,

C'est un add-on HAOS avant tout, j'ai laissé la possibilité de le lancer en dehors du contexte de HAOS en mode best effort, mais ce n'est ni "supporté" ni documenté, l'idée étant que si tu es capable de lancer un container Docker par toi-même, tu es suffisamment avancé pour voir quelles sont les variables d'environnement attendues 😉

Le point d'entrée est ici : https://github.com/marvinroger/hass-addon-tiko/blob/main/tiko/rootfs/docker-entrypoint.sh

En l'occurence, tu peux ignorer cette erreur, c'est simplement le test de si on est dans HAOS ou non qui écrit un log

**Comment by SylvainDx** [comment]
Merci beaucoup pour ton retour ! 
Le fait est que ça fonctionne bien comme ça et c'est le mieux que je puisse demander ! 👍 

Merci encore ^^
