### ISSUE TITLE
[Question] Fonctionnement de l'option "Bypass Schedule"

### ISSUE THREAD

**Issue by SylvainDx** [marvinroger/hass-addon-tiko#19]
Bonjour,

Entre deux réflexion, je me posait la question de l'effet de la fonction : "TIKO_BYPASS_SCHEDULE"

Si je comprend la finalité, je m'interroge sur la méthode.
Il ne me semble pas voir vu l'équivalent sur l'application d'où ma question.

Est-ce que la container sait détecter une modification qui ne viens pas de lui et du coup re-pousse la dernière consigne ?

**Comment by marvinroger** [comment]
Bonjour,

En réalité ce serait mieux nommé "TIKO_OVERRIDE_SCHEDULE", le fonctionnement est d'écraser la programmation tiko en mettant la température de consigne comme programme (tous les jours, de minuit à minuit). De cette manière, la programmation tiko ne prend jamais la main sur la température de consigne.

L'add-on n'est pas capable de détecter une modification qui ne vient pas de lui, mais de fait, à minuit, ça reviendra systématiquement à la température de consigne de l'add-on, le programme ayant été écrasé.

**Comment by SylvainDx** [comment]
ok merci pour ces explications, j'ai du rater quelque chose dans mon setup, j'ai l'impression que Tiko continuait a s'appliquer.
j'ai rajouter le paramètre sur le container existant, il faut surement que je le recrée.

Merci encore
