### ISSUE TITLE
warning - capteur humidité

### ISSUE THREAD

**Issue by phid78** [marvinroger/hass-addon-tiko#2]
Bonsoir marvinroger, 
Mon installation via engie ne comporte plus de thermometre/humidité, le thermoetre est intégré au module sur les nouvelles versions et rien pour l'humidité, j'ai donc un warning : 
```
Logger: homeassistant.helpers.template
Source: helpers/template.py:2318
First occurred: 20:54:20 (44 occurrences)
Last logged: 21:04:20

Template variable warning: 'dict object' has no attribute 'current_humidity' when rendering '{{ value_json.current_humidity }}'
```
est il possible de prevoir une option dans la config pour l'activer ou non ?
en te remerciant, bonne soirée

**Comment by marvinroger** [comment]
Bonsoir !

Est-ce que tu as simplement redémarré Home Assistant puis l'addon ?

C'est un cas relativement rare, et je pense qu'un simple redémarrage devrait mettre à jour les propriétés attendues et régler ce warning.

**Comment by phid78** [comment]
J'ai le warning depuis que j'ai installé ton addon et mon home assistant a redemarrer plusieurs fois depuis. Si je dis pas de betise quand home assistant redemarre,  l'addon redemarre ensuite.
J'ai quand meme essayé d'arreter l'addon, redemarrer home assistant et relancer l'addon mais j'ai toujours le warning.
J'ai peut etre pas compris ce qu'il fallait faire. 
Apres, c'est qu'un warning, donc c'est plus pour te remonter l'info

**Comment by marvinroger** [comment]
Il y'avait en effet un bug, je viens de publier la 1.3.1 qui devrait corriger le warning, est-ce que tu peux me confirmer que c'est bien le cas ?

**Comment by phid78** [comment]
Parfait, il n'y a plus de warning.
Y a t il possibilité de te contacter en privé, je cherche un coup de main stp?

**Comment by marvinroger** [comment]
Tu trouveras mon e-mail en bas de mon site perso (dispo sur la page de profil de mon compte GitHub) 😉

**Comment by phid78** [comment]
salut Marvin, ton mail ne fonctionne pas apparement
