### ISSUE TITLE
How install on the HA Core version

### ISSUE THREAD

**Issue by dlevequeIT** [marvinroger/hass-addon-tiko#3]
Hello,
I'm french and have recently onboarded on MonPilotageElec from Engie.
I found your addon but I'm on the Core version of Home Assistant and the setup button don't work for this setup.
I tried to clone the repo in custom_content folder but it doesn't recognize on HA. So how install/configue please?

**Comment by dlevequeIT** [comment]
Yes it's correct, I installed home assistant manually on my Ubuntu server (without docker) by using the command:
pip3 install homeassistant==2024.1.5

So if I understand well, I should reinstalled by using the docker container to operate "Mon Pilotage Elec" into HA?

**Comment by marvinroger** [comment]
If you look at https://www.home-assistant.io/installation/:

![image](https://github.com/marvinroger/hass-addon-tiko/assets/990773/df6a7c27-0b87-42ed-8daf-592adf602c90)

You see that add-ons are supported in HA OS and HA Supervised. You've chosen the HA Core path which does not provide support for add-on.

For advanced use-cases like yours, I've made the add-on runnable outside of HA OS / Supervised, but the container (not the HA container, but the add-on container) needs to be ran through Docker anyway. You can use the docker cli directly or use something like docker compose.

I'm closing this issue as the add-on officially supports HA OS / Supervised only. 😉

**Comment by dlevequeIT** [comment]
Thanks for the complete answer, I saw that indeed.
I also saw that the docker version which not able to resolve the limitation.

You told me that I can use the Docker Cli to install but I not really have knowledge in docker creation/management. Could you explain me how to setup on my customed server please ?
