### ISSUE TITLE
L'interval de temps entre chaque update n'est pas respecté

### ISSUE THREAD

**Issue by JSteunou** [marvinroger/hass-addon-tiko#8]
Dans les options on peut mettre un *update interval* sauf qu'il n'est pas respecté (ce n'était pas le cas non plus avant la 1.4.1 avec le setInterval)

Le problème [se situe ici](https://github.com/marvinroger/hass-addon-tiko/blob/main/tiko/src/state-updater.ts#L71) `update` se rappelle lui même. Il y a bien [une tempo pour respecter à minima 1 min](https://github.com/marvinroger/hass-addon-tiko/blob/main/tiko/src/state-updater.ts#L47) mais c'est une constante.

L'option est respectée seulement la 1e fois dans le constructeur [ici](https://github.com/marvinroger/hass-addon-tiko/blob/main/tiko/src/state-updater.ts#L27) 

Il faudrait soit : 

* remettre un `setInterval` qui appel `update` tous les X temps et enlever l'auto-appel à la fin de `update`
* soit appeler `update` depuis le constructeur sans `setTimeout` et laisser l'appel récursif mais avec un `setTimeout` de l'interval des options
* soit appeler `update` depuis le constructeur sans `setTimeout`, laisser l'appel récursif et profiter de la tempo au début de l `update` pour dire on attend `Math.max(1, updateIntervalMinutes)`
* ou réponse D (il y a sûrement beaucoup d'autres façons de le faire :smile: )

**Comment by Swiiney** [comment]
Hello, je ne sais pas si il y a un rapport mais depuis la 1.4.1 j'ai des mises à jour bizarres. Le temps entre 2 mise à jour est devenu très long. Ci-joint la courbe d'un de mes thermomètres Tiko (Je suis passé sur la 1.4.1 à 16h le 2/3 au milieu de la courbe).
![image](https://github.com/marvinroger/hass-addon-tiko/assets/19938645/10ad6610-0133-427c-9f47-6a363530a23d)
Toutes mes courbes sont sur le même modèle.

**Comment by marvinroger** [comment]
@JSteunou en effet, j'ai publié la 1.4.2 qui restaure le `setInterval` comme à l'origine.

En fait, le `setInterval` avait toute sa place : si `update` se rappelle tout seul à la fin, c'est en fait voulu.

Imagine que pendant l'appel d'API dans `update`, on change la température de consigne. La température n'aurait été mise à jour qu'au prochain appel de `update`, soit au plus tard dans `updateIntervalMinutes` (donc potentiellement dans longtemps). En s'appelant à la fin de la fonction, on s'assure que le changement d'état sera bien quasi instantané.

Ce n'est pas non plus redondant : si `updateRequested` vaut `false` parce qu'il n'y a pas eu de mouvement, on sort tout de suite de la fonction. 😉

**Comment by marvinroger** [comment]
Le `updateIntervalMinutes` ne veut pas dire "il y'aura au plus un appel tous les `updateIntervalMinutes`", c'est l'intervalle maximum entre deux appels.

Scénario :

* Le `setInterval` appelle `update`
* Pile pendant ce temps, un changement de la température de consigne a lieu. `updateRequested` est donc défini à `true`
* `update` se rappelle lui-même
* `updateRequested` valant `true`, on rafraîchit l'état avec la nouvelle température de consigne. Sans ça, le rafraîchissement n'aurait eu lieu qu'à la prochaine itération de `setInterval`
* `update` se rappelle lui-même
* `updateRequested` valant `false`, on sort de la fonction
* `setInterval` appelle `update`
* `setInterval` appelle `update`
* etc.

Dans le cas nominal, on a donc l'état qui est mis à jour tous les `updateIntervalMinutes`. En revanche, quand un ordre est donné, ce n'est pas tout à fait le cas pour des raisons de réactivité 😉

**Comment by JSteunou** [comment]
Merci pour le scénario déroulé c'est plus clair, effectivement j'étais passé à côté de `updateRequested`
